require'plugins'
require'settings'
require'lsp'

require'setups.bufferline'
require'setups.completion'
require'setups.formatter'
require'setups.kommentary'
require'setups.statusline'
require'setups.subversive'
require'setups.telescope'
require'setups.texmagic'
require'setups.treesitter'
require'setups.vgit'

require'keymap'
