CONFIG_PATH = "$HOME/.config/nvim/"
require "plugins"

require "setups.bufferline"
require "setups.clangd_extensions"
require "setups.formatter"
require "setups.indent_blankline"
require "setups.kommentary"
require "setups.luasnip"
require "setups.neorg"
require "setups.nvim-cmp"
require "setups.rust-tools"
require "setups.statusline"
require "setups.subversive"
require "setups.telescope"
require "setups.treesitter"
require "setups.vimtex"

require "settings"
require "commands"
require "keymap"
require "lsp"
